"use client"

import { createContext, useContext, useState, useEffect, ReactNode } from "react"
import { useRouter, usePathname } from "next/navigation"

export type Language = "en" | "zh"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translations
const translations = {
  en: {
    // Navigation
    "nav.topics": "Topics",
    "nav.login": "Login",
    "nav.signup": "Sign Up",
    "nav.profile": "Profile",
    "nav.logout": "Logout",
    "nav.brand": "ShadowHub",

    // Topics Page
    "topics.title": "English Dictation & Shadowing",
    "topics.subtitle": "Curated English learning materials covering daily life, culture & history, historical speeches, and more. Choose content that matches your level and start practicing!",
    "topics.materials": "materials",
    "topics.categories": "categories",
    "topics.lessons": "lessons",
    "topics.loading": "Loading...",
    "topics.error": "Failed to load materials",
    "topics.errorDetails": "Check the browser console for detailed error information. Possible causes: Supabase connection failed, CORS restrictions, or RLS policy blocking access.",
    "topics.noResults": "No materials found",
    "topics.tryChangingFilters": "Try changing the filter conditions",
    "topics.viewAll": "View All →",
    "topics.collapse": "Collapse ↑",
    "topics.dictation": "Dictation",
    "topics.shadowing": "Shadowing",
    "topics.filter.difficulty": "Difficulty",
    "topics.filter.duration": "Duration",
    "topics.filter.category": "Category",
    "topics.filter.all": "All",
    "topics.filter.short": "Short (< 1min)",
    "topics.filter.medium": "Medium (1-3min)",
    "topics.filter.long": "Long (> 3min)",
    "topics.difficulty.a1": "A1 - Beginner",
    "topics.difficulty.a2": "A2 - Elementary",
    "topics.difficulty.b1": "B1 - Intermediate",
    "topics.difficulty.b2": "B2 - Upper Intermediate",
    "topics.difficulty.c1": "C1 - Advanced",
    "topics.difficulty.c2": "C2 - Proficient",
    "topics.category.dailyLife": "Daily Life",
    "topics.category.historicalSpeeches": "Historical Speeches",
    "topics.category.cultureHistory": "Culture & History",
    "topics.category.artsCulture": "Arts & Culture",

    // Practice Page
    "practice.loading": "Loading...",
    "practice.fetchError": "Failed to load material",
    "practice.notFound": "Material not found",
    "practice.tryAnother": "Please try another material",
    "practice.mode.dictation": "Dictation",
    "practice.mode.shadowing": "Shadowing Practice",
    "practice.dictation.word": "Word Mode",
    "practice.dictation.whole": "Sentence Mode",
    "practice.dictationMode.word": "Word",
    "practice.dictationMode.whole": "Whole Caption",
    "practice.dictationMode.label": "Dictation mode",
    "practice.dictation.showTranslation": "Show Translation",
    "practice.dictation.hideTranslation": "Hide Translation",
    "practice.dictation.typeWhatYouHear": "Type what you hear",
    "practice.dictation.typeYourAnswer": "Type your answer here...",
    "practice.dictation.correct": "✓ Correct!",
    "practice.dictation.incorrect": "Not correct. Please try again.",
    "practice.dictation.showWordsConfirm1": "Are you sure you want to show all words and submit your answer?",
    "practice.dictation.showWordsConfirm2": "The score for this sentence will be reduced according to the number of words you have not shown ({count} words).",
    "practice.wordMode.typeMissingWord": "Type the missing word",
    "practice.wordMode.correctShown": "Correct answer shown (editable)",
    "practice.wordMode.incorrect": "Not correct. Please listen again and try!",
    "practice.wordMode.showWord": "Show Word",
    "practice.shadowing.tip": "Shadowing: Play audio and click microphone to follow",
    "practice.shadowing.showAll": "Show All",
    "practice.shadowing.translationOnly": "Translation Only",
    "practice.shadowing.hideAll": "Hide All",
    "practice.shadowing.original": "Original",
    "practice.shadowing.translation": "Translation",
    "practice.shadowing.blindMode": "Blind Mode - Listen and shadow without text",
    "practice.shadowing.myPronunciation": "My pronunciation",
    "practice.shadowing.noRecognition": "Could not recognize speech, please try again",
    "practice.shadowing.linkingTips": "Linking Tips",
    "practice.shadowing.canBeLinked": "can be linked",
    "practice.shadowing.pronouncedAs": "pronounced as",
    "practice.shadowing.perfectPronunciation": "Perfect pronunciation!",
    "practice.shadowing.keepPracticing": "Keep practicing!",
    "practice.shadowing.audioComparison": "Audio Comparison",
    "practice.shadowing.originalAudio": "Original",
    "practice.shadowing.myRecording": "My Recording",
    "practice.shadowing.recording": "🎤 Recording...",
    "practice.shadowing.record": "Record",
    "practice.shadowing.submit": "Submit Recording",
    "practice.sentencesCompleted": "completed",
    "practice.showWords": "Show Words",
    "practice.showAllWords": "Show All Words",
    "practice.hideWords": "Hide Words",
    "practice.checkAnswer": "Check",
    "practice.playRecording": "Play Recording",
    "practice.reRecord": "Re-record",
    "practice.submit": "Submit",
    "practice.playOriginal": "Play Original",
    "practice.shadowing.title": "Shadowing Practice",
    "practice.dictation.title": "Dictation Practice",
    "practice.sentence": "Sentence",
    "practice.of": "of",
    "practice.transcript.show": "Show Transcript",
    "practice.transcript.hide": "Hide Transcript",
    "practice.transcript.title": "Transcript",
    "practice.playbackRate": "Speed",
    "practice.speed": "Speed",
    "practice.replay": "Replay",
    "practice.next": "Next",
    "practice.previous": "Previous",
    "practice.backToMaterials": "Back to Materials",
    "practice.audioError": "Audio not available",
    "practice.tryRefreshing": "Please try refreshing the page",
    "practice.breadcrumb.topics": "Topics",

    // Hero
    "hero.title.line1": "Master English Through Dictation",
    "hero.title.line2": "& Shadowing",
    "hero.subtitle": "Improve your listening and speaking skills with AI-powered practice tools",
    "hero.cta": "Start Learning Free",

    // Auth Modal
    "auth.title": "Unlock Your Learning Progress",
    "auth.subtitle": "Register to save practice records, track your progress, and view detailed statistics",
    "auth.feature1.title": "Auto-save Practice Records",
    "auth.feature1.desc": "Never lose your practice history",
    "auth.feature2.title": "View Detailed Statistics",
    "auth.feature2.desc": "Track accuracy, completion, and streaks",
    "auth.feature3.title": "Track Learning Progress",
    "auth.feature3.desc": "Monitor your improvement over time",
    "auth.signup": "Sign Up Free",
    "auth.login": "Log In",
    "auth.noCredit": "No credit card required • Start learning in seconds",
    "auth.close": "Close",

    // How It Works
    "how.title": "How It Works",
    "how.subtitle": "Only 4 steps, making English practice easier and more enjoyable",
    "how.step1.title": "Choose Material",
    "how.step1.desc": "Select from our curated collection of English audio materials",
    "how.step2.title": "Select Mode",
    "how.step2.desc": "Choose between Dictation or Shadowing practice mode",
    "how.step3.title": "Practice",
    "how.step3.desc": "Listen and practice at your own pace with AI assistance",
    "how.step4.title": "Track Progress",
    "how.step4.desc": "View your statistics and monitor your improvement over time",

    // Features
    "features.title": "Powerful Features for Effective Learning",
    "feature.dictation.title": "Word-by-Word Dictation, Precise Improvement",
    "feature.dictation.desc": "Strengthen English listening comprehension through word-by-word dictation training.",
    "feature.dictation.word": "Word Mode",
    "feature.dictation.wordDesc": "Dictate word by word, enter each word independently, suitable for beginners",
    "feature.dictation.sentence": "Sentence Mode",
    "feature.dictation.sentenceDesc": "Listen to the full sentence then enter, train complete sentence comprehension",
    "feature.dictation.feedback": "Instant Feedback",
    "feature.dictation.feedbackDesc": "AI real-time comparison, precisely locate spelling errors",
    "feature.dictation.levels": "Multiple Difficulty Levels",
    "feature.dictation.speed": "Adjustable Playback Speed",
    "feature.dictation.hint": "Hint Function",
    "feature.dictation.try": "Try now",
    "feature.dictation.wordMode": "Word Mode",
    "feature.dictation.correct": "Correct",
    "feature.dictation.playing": "Playing...",
    "feature.dictation.wordN": "Word",
    "feature.dictation.checkAnswer": "Check Answer",
    "feature.dictation.typeWhatYouHear": "Type what you hear...",

    "feature.shadowing.title": "Shadowing Practice, Improve Speaking",
    "feature.shadowing.desc": "Shadow the native speaker audio to improve pronunciation, intonation, and speaking speed.",
    "feature.shadowing.record": "Record Your Voice",
    "feature.shadowing.recordDesc": "Record your pronunciation and compare with native speaker audio",
    "feature.shadowing.ai": "AI Pronunciation Analysis",
    "feature.shadowing.aiDesc": "Get instant feedback on pronunciation accuracy and fluency",
    "feature.shadowing.progress": "Track Speaking Progress",
    "feature.shadowing.progressDesc": "Monitor your improvement in pronunciation and fluency over time",
    "feature.shadowing.try": "Try now",
    "feature.shadowing.title2": "Mimic Native Speakers, Master Authentic Pronunciation",
    "feature.shadowing.desc2": "Shadowing is the golden method for language learning. Through synchronized repetition, train oral muscle memory and master authentic intonation and linking techniques.",
    "feature.shadowing.sync": "Synchronized Repetition",
    "feature.shadowing.syncDesc": "Sync with the original audio, train instant reaction ability",
    "feature.shadowing.linking": "Linking Tips",
    "feature.shadowing.linkingDesc": "Intelligently mark linking positions, master natural fluency",
    "feature.shadowing.intonation": "Intonation Mimicry",
    "feature.shadowing.intonationDesc": "Learn stress, pauses, and intonation changes",
    "feature.shadowing.fluency": "Improve Speaking Fluency",
    "feature.shadowing.pronunciation": "Correct Pronunciation Issues",
    "feature.shadowing.scoring": "AI Scoring Feedback",
    "feature.shadowing.clickToRecord": "Click to start recording",
    "feature.shadowing.linkingTipExample": "Linking Tip: sister_and links to /sɪstərənd/",
    "feature.shadowing.mimicIntonation": "Mimic Intonation",
    "feature.shadowing.sentenceN": "Sentence",

    "feature.ai.title": "AI Intelligent Correction",
    "feature.ai.desc": "Advanced AI technology analyzes your pronunciation and spelling errors, providing precise correction suggestions.",
    "feature.ai.pronunciation": "Pronunciation Analysis",
    "feature.ai.pronunciationDesc": "AI analyzes your pronunciation and provides improvement suggestions",
    "feature.ai.spelling": "Spelling Check",
    "feature.ai.spellingDesc": "Automatically detect spelling errors and provide correct spelling",
    "feature.ai.fluency": "Fluency Assessment",
    "feature.ai.fluencyDesc": "Evaluate speaking fluency and rhythm, help improve naturalness",
    "feature.ai.smart": "AI Smart Correction",
    "feature.ai.title2": "Precise Diagnosis, Targeted Improvement",
    "feature.ai.desc2": "Say goodbye to blind practice. AI intelligently analyzes your input, precisely locates error types, and provides personalized improvement suggestions, making every practice session clearly rewarding.",
    "feature.ai.spell": "Spell Check",
    "feature.ai.spellDesc": "Automatically identify spelling errors and capitalization issues",
    "feature.ai.linking": "Linking Suggestions",
    "feature.ai.linkingDesc": "Suggest natural linking methods, improve speaking fluency",
    "feature.ai.analysis": "Error Analysis",
    "feature.ai.analysisDesc": "Categorize and count error types, discover weak areas",
    "feature.ai.trend": "Error Trend Tracking",
    "feature.ai.personalized": "Personalized Suggestions",
    "feature.ai.realtime": "Real-time Feedback",
    "feature.ai.diagnostic": "AI Diagnostic Report",
    "feature.ai.original": "Original Text",
    "feature.ai.input": "Your Input",
    "feature.ai.subjectVerb": "Subject-Verb Agreement Error",
    "feature.ai.improvement": "Improvement Suggestion",
    "feature.ai.accuracy": "Accuracy",
    "feature.ai.errors": "Errors",
    "feature.ai.grade": "Grade",
    "feature.ai.try": "Try now",

    "feature.growth.title": "Growth Tracking, Visible Progress",
    "feature.growth.desc": "Comprehensive statistics help you understand your learning situation and keep motivated.",
    "feature.growth.accuracy": "Accuracy Rate",
    "feature.growth.accuracyDesc": "Track dictation and shadowing accuracy trends",
    "feature.growth.streak": "Learning Streak",
    "feature.growth.streakDesc": "Maintain continuous learning habits and earn achievement badges",
    "feature.growth.history": "Practice History",
    "feature.growth.historyDesc": "Review all practice records and analyze mistakes",
    "feature.growth.tracking": "Growth Tracking",
    "feature.growth.title2": "Visualize Progress, Stay Motivated",
    "feature.growth.desc2": "Every step of learning is recorded. Through detailed statistics and visualization charts, clearly see your growth trajectory, making persistence more meaningful.",
    "feature.growth.practice": "Practice Statistics",
    "feature.growth.practiceDesc": "Track daily practice count, duration, and accuracy",
    "feature.growth.streakRecord": "Streak Records",
    "feature.growth.streakRecordDesc": "Track consecutive learning days, maintain study habits",
    "feature.growth.charts": "Progress Charts",
    "feature.growth.chartsDesc": "Visual charts display learning trends",
    "feature.growth.achievement": "Achievement System",
    "feature.growth.achievementDesc": "Unlock badges and milestones, motivate continuous learning",
    "feature.growth.statistics": "Learning Statistics",
    "feature.growth.pastDays": "Past 7 days",
    "feature.growth.dayStreak": "Day Streak",
    "feature.growth.totalPractices": "Total Practices",
    "feature.growth.avgAccuracy": "Avg. Accuracy",
    "feature.growth.todayActivity": "Today's Activity",
    "feature.growth.completed": "Completed",
    "feature.growth.sentences": "sentences",
    "feature.growth.practiceTime": "Practice Time",
    "feature.growth.dictationPractice": "Dictation Practice",
    "feature.growth.detailedData": "Detailed Data",
    "feature.growth.achievementBadges": "Achievement Badges",
    "feature.growth.studyHabits": "Study Habits",
    "feature.growth.try": "Try now",

    // FAQ
    "faq.title": "Frequently Asked Questions",
    "faq.subtitle": "Quickly find answers to common questions about this tool",
    "faq.q1.title": "What are Dictation and Shadowing?",
    "faq.q1.answer": "They are the \"Power Duo\" of language learning. Dictation acts like a microscope for your ears, helping you catch every hidden detail. Shadowing works like a \"human photocopier\"—you mimic native speakers in real-time (without looking at text) to engrave authentic rhythm and intonation directly into your speech muscles.",
    "faq.q2.title": "Why can't I understand native speakers after years of study?",
    "faq.q2.answer": "Textbooks teach isolated, \"perfect\" sounds, but real life is full of Linking and Reductions. Our dual-mode dictation (Word + Full Sentence) forces your brain to recognize these \"invisible sounds,\" turning blurry audio into crystal-clear English.",
    "faq.q3.title": "Is this tool suitable for beginners?",
    "faq.q3.answer": "Absolutely! We've designed the platform for everyone. Our content is organized by difficulty, so you can start with basics that match your current level and gradually level up as you gain confidence.",
    "faq.q4.title": "I always forget words. Will this method help?",
    "faq.q4.answer": "Rote memorization is dead weight; Dictation and Shadowing are active internalization. Here, words aren't just stored—they're used. By hearing, writing, and speaking them in real-world contexts with various native accents, you build a \"living memory\" that sticks for good.",
    "faq.q5.title": "What kind of content do you provide?",
    "faq.q5.answer": "We offer a massive library of real-world materials, including TV shows, interviews, fairy tales, daily conversations, BBC, and VOA. Every piece of content is hand-picked to ensure you're learning English that people actually use.",
    "faq.q6.title": "Do I need to register an account?",
    "faq.q6.answer": "No registration required to start practicing. However, if you register an account, you can save practice records, view detailed statistics, track learning progress, and get a better personalized experience.",
    "faq.q7.title": "What's the difference between Dictation and Shadowing modes?",
    "faq.q7.answer": "Dictation mode trains listening comprehension and spelling through word-by-word or full-sentence dictation; Shadowing trains speaking pronunciation, intonation, and fluency through synchronized repetition. Using both methods together can comprehensively improve your English level.",
    "faq.q8.title": "How do I choose suitable materials?",
    "faq.q8.answer": "We recommend choosing based on your English level: beginners can select daily conversations or stories with slower speed and simpler vocabulary; intermediate and advanced learners can try more challenging content like news and speeches. The library has different difficulty levels for you to choose from.",
    "faq.q9.title": "How does the AI error correction work?",
    "faq.q9.answer": "AI intelligently compares your input with the original text, identifying spelling errors, grammar issues, missing or extra words. The system highlights error locations and provides correct answers and improvement suggestions to help you practice targetedly.",
    "faq.q10.title": "Will my practice data be saved?",
    "faq.q10.answer": "If you register and log in, all practice records will be automatically saved to the cloud. You can view detailed statistics, practice history, and progress curves in your personal center. Practice data for non-logged-in users is only saved locally in the browser.",
    "faq.q11.title": "Can I customize practice content?",
    "faq.q11.answer": "We currently provide curated English learning materials. Future versions will support users uploading their own audio content to create personalized practice materials.",
    "faq.q12.title": "Do you support mobile devices?",
    "faq.q12.answer": "Fully supported! Our tool uses responsive design and works smoothly on computers, tablets, and mobile phones. Practice anytime, anywhere.",
    "faq.q13.title": "How do I get started?",
    "faq.q13.answer": "It's easy! Sign up for a free account, pick a topic that interests you, and start your journey toward fluency today.",

    // CTA
    "cta.title": "Stop 'Not Understanding, Not Speaking Out'",
    "cta.subtitle": "10 minutes of Dictation + Shadowing daily, transform English from an 'exam tool' into a language you can truly use.",
    "cta.button": "Start Learning",
    "cta.contact": "Contact Us",
    "cta.github": "GitHub",

    // Footer
    "footer.about": "About",
    "footer.aboutDesc": "A professional English dictation and shadowing practice tool to help you efficiently improve your listening and speaking skills.",
    "footer.features": "Features",
    "footer.dictation": "Dictation Practice",
    "footer.shadowing": "Shadowing Practice",
    "footer.materials": "Materials",
    "footer.resources": "Resources",
    "footer.github": "GitHub",
    "footer.contact": "Contact Us",
    "footer.rights": "All rights reserved.",
  },
  zh: {
    // Navigation
    "nav.topics": "素材",
    "nav.login": "登录",
    "nav.signup": "注册",
    "nav.profile": "个人中心",
    "nav.logout": "退出登录",
    "nav.brand": "语言跟读",

    // Topics Page
    "topics.title": "英语听写和影子跟读",
    "topics.subtitle": "精心策划的英语学习素材，涵盖日常生活、文化历史、历史演讲等。选择适合您水平的内容，开始练习吧！",
    "topics.materials": "个素材",
    "topics.categories": "个分类",
    "topics.lessons": "个课程",
    "topics.loading": "加载中...",
    "topics.error": "加载素材失败",
    "topics.errorDetails": "请查看浏览器控制台获取详细错误信息。可能原因：Supabase 连接失败、CORS 限制或 RLS 策略阻止访问。",
    "topics.noResults": "未找到素材",
    "topics.tryChangingFilters": "尝试更改筛选条件",
    "topics.viewAll": "查看全部 →",
    "topics.collapse": "收起 ↑",
    "topics.dictation": "听写",
    "topics.shadowing": "影子跟读",
    "topics.filter.difficulty": "难度",
    "topics.filter.duration": "时长",
    "topics.filter.category": "分类",
    "topics.filter.all": "全部",
    "topics.filter.short": "短音频 (< 1分钟)",
    "topics.filter.medium": "中等 (1-3分钟)",
    "topics.filter.long": "长音频 (> 3分钟)",
    "topics.difficulty.a1": "A1 - 初级",
    "topics.difficulty.a2": "A2 - 入门",
    "topics.difficulty.b1": "B1 - 中级",
    "topics.difficulty.b2": "B2 - 中高级",
    "topics.difficulty.c1": "C1 - 高级",
    "topics.difficulty.c2": "C2 - 精通",
    "topics.category.dailyLife": "日常生活",
    "topics.category.historicalSpeeches": "历史演讲",
    "topics.category.cultureHistory": "文化历史",
    "topics.category.artsCulture": "艺术文化",

    // Practice Page
    "practice.loading": "加载中...",
    "practice.fetchError": "加载素材失败",
    "practice.notFound": "素材未找到",
    "practice.tryAnother": "请尝试其他素材",
    "practice.mode.dictation": "听写",
    "practice.mode.shadowing": "影子跟读",
    "practice.dictation.word": "单词模式",
    "practice.dictation.whole": "整句模式",
    "practice.dictationMode.word": "单词",
    "practice.dictationMode.whole": "整句",
    "practice.dictationMode.label": "听写模式",
    "practice.dictation.showTranslation": "显示译文",
    "practice.dictation.hideTranslation": "隐藏译文",
    "practice.dictation.typeWhatYouHear": "输入您听到的内容",
    "practice.dictation.typeYourAnswer": "在此输入您的答案...",
    "practice.dictation.correct": "✓ 正确！",
    "practice.dictation.incorrect": "不正确，请重试。",
    "practice.dictation.showWordsConfirm1": "确定要显示所有单词并提交答案吗？",
    "practice.dictation.showWordsConfirm2": "本句分数将根据您未显示的单词数量（{count} 个单词）相应降低。",
    "practice.wordMode.typeMissingWord": "输入缺失的单词",
    "practice.wordMode.correctShown": "已显示正确答案（可编辑）",
    "practice.wordMode.incorrect": "不正确，请再听一次再试！",
    "practice.wordMode.showWord": "显示单词",
    "practice.shadowing.tip": "影子跟读：播放音频后，点击麦克风跟读",
    "practice.shadowing.showAll": "显示全部",
    "practice.shadowing.translationOnly": "仅译文",
    "practice.shadowing.hideAll": "隐藏全部",
    "practice.shadowing.original": "原文",
    "practice.shadowing.translation": "译文",
    "practice.shadowing.blindMode": "盲听模式 - 不看文本跟读",
    "practice.shadowing.myPronunciation": "我的发音",
    "practice.shadowing.noRecognition": "无法识别语音，请重试",
    "practice.shadowing.linkingTips": "连读技巧",
    "practice.shadowing.canBeLinked": "可以连读",
    "practice.shadowing.pronouncedAs": "发音为",
    "practice.shadowing.perfectPronunciation": "发音完美！",
    "practice.shadowing.keepPracticing": "继续加油！",
    "practice.shadowing.audioComparison": "音频对比",
    "practice.shadowing.originalAudio": "原声",
    "practice.shadowing.myRecording": "我的录音",
    "practice.shadowing.recording": "🎤 正在录音...",
    "practice.shadowing.record": "录音",
    "practice.shadowing.submit": "提交录音",
    "practice.sentencesCompleted": "已完成",
    "practice.showWords": "显示单词",
    "practice.showAllWords": "显示所有单词",
    "practice.hideWords": "隐藏单词",
    "practice.checkAnswer": "检查答案",
    "practice.playRecording": "播放录音",
    "practice.reRecord": "重新录制",
    "practice.submit": "提交",
    "practice.playOriginal": "播放原声",
    "practice.shadowing.title": "影子跟读练习",
    "practice.dictation.title": "听写练习",
    "practice.sentence": "句子",
    "practice.of": "/",
    "practice.transcript.show": "显示原文",
    "practice.transcript.hide": "隐藏原文",
    "practice.transcript.title": "原文",
    "practice.playbackRate": "速度",
    "practice.speed": "速度",
    "practice.replay": "重新播放",
    "practice.next": "下一句",
    "practice.previous": "上一句",
    "practice.backToMaterials": "返回素材",
    "practice.audioError": "音频不可用",
    "practice.tryRefreshing": "请尝试刷新页面",
    "practice.breadcrumb.topics": "素材",

    // Hero
    "hero.title.line1": "通过听写和跟读",
    "hero.title.line2": "让英语脱口而出",
    "hero.subtitle": "通过互动听写和影子跟读练习，提升您的英语听力和英语口语技能。获取 AI 反馈和分级内容，适合所有水平的英语学习者。",
    "hero.cta": "免费开始学习",

    // Auth Modal
    "auth.title": "解锁您的学习进度",
    "auth.subtitle": "注册账号即可保存练习记录，追踪学习进度，查看详细统计数据",
    "auth.feature1.title": "自动保存练习记录",
    "auth.feature1.desc": "永不丢失练习历史",
    "auth.feature2.title": "查看详细统计数据",
    "auth.feature2.desc": "追踪准确率、完成度和连续记录",
    "auth.feature3.title": "追踪学习进度",
    "auth.feature3.desc": "监控您的进步",
    "auth.signup": "免费注册",
    "auth.login": "登录",
    "auth.noCredit": "无需信用卡 • 秒速开始学习",
    "auth.close": "关闭",

    // How It Works
    "how.title": "如何使用",
    "how.subtitle": "只需 4 个步骤，让英语练习更简单、更有趣",
    "how.step1.title": "选择素材",
    "how.step1.desc": "从我们精心策划的英语音频素材库中选择",
    "how.step2.title": "选择模式",
    "how.step2.desc": "选择听写或跟读练习模式",
    "how.step3.title": "开始练习",
    "how.step3.desc": "按照自己的节奏练习，AI 助手全程陪伴",
    "how.step4.title": "追踪进度",
    "how.step4.desc": "查看统计数据，监控您的进步",

    // Features
    "features.title": "强大的功能，高效的学习",
    "feature.dictation.title": "逐词听写，精准提升",
    "feature.dictation.desc": "通过逐词听写训练加强英语听力理解能力。",
    "feature.dictation.word": "单词模式",
    "feature.dictation.wordDesc": "逐词听写，独立输入每个单词，适合初学者",
    "feature.dictation.sentence": "整句模式",
    "feature.dictation.sentenceDesc": "听完整句后输入，训练完整句子理解",
    "feature.dictation.feedback": "即时反馈",
    "feature.dictation.feedbackDesc": "AI 实时对比，精准定位拼写错误",
    "feature.dictation.levels": "多种难度等级",
    "feature.dictation.speed": "可调节播放速度",
    "feature.dictation.hint": "提示功能",
    "feature.dictation.try": "立即尝试",
    "feature.dictation.wordMode": "单词模式",
    "feature.dictation.correct": "正确",
    "feature.dictation.playing": "播放中...",
    "feature.dictation.wordN": "单词",
    "feature.dictation.checkAnswer": "检查答案",
    "feature.dictation.typeWhatYouHear": "输入您听到的内容...",

    "feature.shadowing.title": "影子跟读，提升口语",
    "feature.shadowing.desc": "跟读原声音频，改善发音、语调和语速。",
    "feature.shadowing.record": "录制声音",
    "feature.shadowing.recordDesc": "录制您的发音并与原声对比",
    "feature.shadowing.ai": "AI 发音分析",
    "feature.shadowing.aiDesc": "获得发音准确度和流利度的即时反馈",
    "feature.shadowing.progress": "追踪口语进步",
    "feature.shadowing.progressDesc": "监控发音和流利度的提升",
    "feature.shadowing.try": "立即尝试",
    "feature.shadowing.title2": "模仿母语者，掌握地道发音",
    "feature.shadowing.desc2": "跟读是语言学习的黄金方法。通过同步重复，训练口腔肌肉记忆，掌握地道语调和连读技巧。",
    "feature.shadowing.sync": "同步重复",
    "feature.shadowing.syncDesc": "与原声同步，训练即时反应能力",
    "feature.shadowing.linking": "连读技巧",
    "feature.shadowing.linkingDesc": "智能标记连读位置，掌握自然流畅度",
    "feature.shadowing.intonation": "语调模仿",
    "feature.shadowing.intonationDesc": "学习重音、停顿和语调变化",
    "feature.shadowing.fluency": "提升口语流利度",
    "feature.shadowing.pronunciation": "纠正发音问题",
    "feature.shadowing.scoring": "AI 评分反馈",
    "feature.shadowing.clickToRecord": "点击开始录音",
    "feature.shadowing.linkingTipExample": "连读提示：sister_and 连读为 /sɪstərənd/",
    "feature.shadowing.mimicIntonation": "模仿语调",
    "feature.shadowing.sentenceN": "句子",

    "feature.ai.title": "AI 智能纠错",
    "feature.ai.desc": "先进的 AI 技术分析您的发音和拼写错误，提供精准的改进建议。",
    "feature.ai.pronunciation": "发音分析",
    "feature.ai.pronunciationDesc": "AI 分析您的发音并提供改进建议",
    "feature.ai.spelling": "拼写检查",
    "feature.ai.spellingDesc": "自动检测拼写错误并提供正确拼写",
    "feature.ai.fluency": "流利度评估",
    "feature.ai.fluencyDesc": "评估口语流利度和节奏，帮助提升自然度",
    "feature.ai.smart": "AI 智能纠错",
    "feature.ai.title2": "精准诊断，针对性提升",
    "feature.ai.desc2": "告别盲目练习。AI 智能分析您的输入，精准定位错误类型，提供个性化改进建议，让每次练习都有明确收获。",
    "feature.ai.spell": "拼写检查",
    "feature.ai.spellDesc": "自动识别拼写错误和大小写问题",
    "feature.ai.linking": "连读建议",
    "feature.ai.linkingDesc": "建议自然连读方法，提升口语流利度",
    "feature.ai.analysis": "错误分析",
    "feature.ai.analysisDesc": "分类统计错误类型，发现薄弱环节",
    "feature.ai.trend": "错误趋势追踪",
    "feature.ai.personalized": "个性化建议",
    "feature.ai.realtime": "实时反馈",
    "feature.ai.diagnostic": "AI 诊断报告",
    "feature.ai.original": "原文",
    "feature.ai.input": "您的输入",
    "feature.ai.subjectVerb": "主谓一致错误",
    "feature.ai.improvement": "改进建议",
    "feature.ai.accuracy": "准确率",
    "feature.ai.errors": "错误数",
    "feature.ai.grade": "等级",
    "feature.ai.try": "立即尝试",

    "feature.growth.title": "成长追踪，进步可见",
    "feature.growth.desc": "全面的统计数据帮助您了解学习情况，保持学习动力。",
    "feature.growth.accuracy": "准确率",
    "feature.growth.accuracyDesc": "追踪听写和跟读的准确率趋势",
    "feature.growth.streak": "学习连续记录",
    "feature.growth.streakDesc": "保持连续学习习惯，获得成就徽章",
    "feature.growth.history": "练习历史",
    "feature.growth.historyDesc": "查看所有练习记录，分析错误",
    "feature.growth.tracking": "成长追踪",
    "feature.growth.title2": "可视化进度，保持动力",
    "feature.growth.desc2": "学习的每一步都被记录。通过详细统计和可视化图表，清晰看到您的成长轨迹，让坚持更有意义。",
    "feature.growth.practice": "练习统计",
    "feature.growth.practiceDesc": "追踪每日练习次数、时长和准确率",
    "feature.growth.streakRecord": "连续记录",
    "feature.growth.streakRecordDesc": "追踪连续学习天数，保持学习习惯",
    "feature.growth.charts": "进度图表",
    "feature.growth.chartsDesc": "可视化图表展示学习趋势",
    "feature.growth.achievement": "成就系统",
    "feature.growth.achievementDesc": "解锁徽章和里程碑，激励持续学习",
    "feature.growth.statistics": "学习统计",
    "feature.growth.pastDays": "过去 7 天",
    "feature.growth.dayStreak": "天连续",
    "feature.growth.totalPractices": "总练习数",
    "feature.growth.avgAccuracy": "平均准确率",
    "feature.growth.todayActivity": "今日活动",
    "feature.growth.completed": "完成",
    "feature.growth.sentences": "句",
    "feature.growth.practiceTime": "练习时长",
    "feature.growth.dictationPractice": "听写练习",
    "feature.growth.detailedData": "详细数据",
    "feature.growth.achievementBadges": "成就徽章",
    "feature.growth.studyHabits": "学习习惯",
    "feature.growth.try": "立即尝试",

    // FAQ
    "faq.title": "常见问题",
    "faq.subtitle": "快速找到关于此工具的常见问题答案",
    "faq.q1.title": "什么是听写和跟读？",
    "faq.q1.answer": "它们是语言学习的\"黄金搭档\"。听写就像耳边的显微镜，帮助您捕捉每个隐藏细节。跟读就像\"人类复印机\"——您实时模仿母语者（不看文本）将地道节奏和语调直接刻入您的演讲肌肉。",
    "faq.q2.title": "为什么学习多年还是听不懂母语者？",
    "faq.q2.answer": "教科书教的是孤立的\"完美\"发音，但现实生活充满连读和弱化。我们的双模式听写（单词+整句）强迫您的大脑识别这些\"隐形声音\"，将模糊音频转化为清晰的英语。",
    "faq.q3.title": "这个工具适合初学者吗？",
    "faq.q3.answer": "当然可以！我们为每个人设计了这个平台。内容按难度分级，您可以从适合当前水平的基础开始，随着信心增强逐步升级。",
    "faq.q4.title": "我总是记不住单词。这种方法有帮助吗？",
    "faq.q4.answer": "死记硬背是沉重负担；听写和跟读是主动内化。在这里，单词不仅被储存——它们被使用。通过在各种真实语境和不同母语口音中听、写、说，您将建立\"活体记忆\"，持久难忘。",
    "faq.q5.title": "你们提供什么类型的内容？",
    "faq.q5.answer": "我们提供海量真实材料库，包括电视剧、访谈、童话、日常对话、BBC 和 VOA。每篇内容都是精心挑选，确保您学习的是人们真正使用的英语。",
    "faq.q6.title": "需要注册账号吗？",
    "faq.q6.answer": "开始练习无需注册。但是，如果您注册账号，可以保存练习记录、查看详细统计、追踪学习进度，获得更好的个性化体验。",
    "faq.q7.title": "听写和跟读模式有什么区别？",
    "faq.q7.answer": "听写模式通过逐词或整句听写训练听力理解和拼写；跟读模式通过同步重复训练口语发音、语调和流利度。两种方法结合使用可以全面提升英语水平。",
    "faq.q8.title": "如何选择合适的素材？",
    "faq.q8.answer": "我们建议根据英语水平选择：初学者可以选择语速较慢、词汇较简单的日常对话或故事；中高级学习者可以尝试更有挑战性的新闻和演讲。素材库有不同难度等级供您选择。",
    "faq.q9.title": "AI 纠错如何工作？",
    "faq.q9.answer": "AI 智能对比您的输入与原文，识别拼写错误、语法问题、漏词或多词。系统会高亮错误位置并提供正确答案和改进建议，帮助您有针对性地练习。",
    "faq.q10.title": "我的练习数据会被保存吗？",
    "faq.q10.answer": "如果您注册并登录，所有练习记录将自动保存到云端。您可以在个人中心查看详细统计、练习历史和进度曲线。未登录用户的练习数据仅在浏览器本地保存。",
    "faq.q11.title": "我可以自定义练习内容吗？",
    "faq.q11.answer": "我们目前提供精选的英语学习材料。未来版本将支持用户上传自己的音频内容来创建个性化练习材料。",
    "faq.q12.title": "支持移动设备吗？",
    "faq.q12.answer": "完全支持！我们的工具采用响应式设计，在电脑、平板和手机上都能流畅运行。随时随地练习。",
    "faq.q13.title": "如何开始？",
    "faq.q13.answer": "很简单！注册免费账号，选择您感兴趣的主题，今天就开启您的流利之旅。",

    // CTA
    "cta.title": "告别听不懂、说不出",
    "cta.subtitle": "每天 10 分钟听写+跟读，把英语从考试工具变成真正能用的语言。",
    "cta.button": "开始学习",
    "cta.contact": "联系我们",
    "cta.github": "GitHub",

    // Footer
    "footer.about": "关于",
    "footer.aboutDesc": "专业的英语听写和跟读练习工具，帮助您高效提升听说能力。",
    "footer.features": "功能",
    "footer.dictation": "听写练习",
    "footer.shadowing": "影子跟读",
    "footer.materials": "素材",
    "footer.resources": "资源",
    "footer.github": "GitHub",
    "footer.contact": "联系我们",
    "footer.rights": "版权所有。",
  },
}

interface LanguageProviderProps {
  children: ReactNode
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    // Detect language from localStorage or cookie
    const savedLang = localStorage.getItem("language") as Language
    if (savedLang && (savedLang === "en" || savedLang === "zh")) {
      setLanguage(savedLang)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations["en"]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
