#!/usr/bin/env node
/**
 * 从 Supabase 同步所有素材的 slug 到 materialSlugs.ts
 * 运行方式: node scripts/sync-slugs.js
 */

const { createClient } = require('@supabase/supabase-js')

const supabaseUrl = 'https://cuxotlijjnxbsirpdkgr.supabase.co'
const supabaseKey = 'sb_publishable_UeaK10sYGQPjB17Vg-IpcQ_ql3xHKMm'

const supabase = createClient(supabaseUrl, supabaseKey)

// titleToSlug 函数（从 src/lib/utils/slug.ts 复制）
function titleToSlug(title) {
  if (!title) return ''
  return title
    .toLowerCase()
    .replace(/[^\w\s-]/g, '') // 移除特殊字符
    .replace(/_/g, '-') // 下划线替换为连字符
    .replace(/\s+/g, '-') // 空格替换为连字符
    .replace(/-+/g, '-') // 多个连字符合并为一个
    .replace(/^-+|-+$/g, '') // 移除首尾连字符
    .substring(0, 200) // 限制长度
}

async function syncSlugs() {
  try {
    console.log('📡 从 Supabase 获取所有素材...')
    const { data: materials, error } = await supabase
      .from('materials')
      .select('title')

    if (error) {
      console.error('❌ 获取素材失败:', error)
      process.exit(1)
    }

    if (!materials || materials.length === 0) {
      console.log('⚠️  没有找到任何素材')
      process.exit(0)
    }

    console.log(`✅ 找到 ${materials.length} 个素材`)

    // 生成 slugs 数组
    const slugs = materials
      .map(m => {
        const slug = titleToSlug(m.title)
        return `  { slug: "${slug}" },`
      })
      .sort()

    // 生成文件内容
    const fileContent = `// Material slugs fetched from Supabase
// This file is auto-generated by scripts/sync-slugs.js
// DO NOT EDIT MANUALLY - run the script to update
export const MATERIAL_SLUGS = [
${slugs.join('\n')}
]
`

    // 写入文件
    const fs = require('fs')
    const filePath = './src/lib/data/materialSlugs.ts'

    fs.writeFileSync(filePath, fileContent, 'utf8')
    console.log(`✅ 已更新 ${filePath}`)
    console.log(`📝 共 ${slugs.length} 个 slug`)

    // 验证：检查是否有重复的 slug
    const uniqueSlugs = new Set(slugs)
    if (uniqueSlugs.size !== slugs.length) {
      console.log('⚠️  警告：发现重复的 slug！')
    }

  } catch (error) {
    console.error('❌ 同步失败:', error)
    process.exit(1)
  }
}

syncSlugs()
